package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
)

type config struct {
	nextURL     string
	previousURL string
}

type cliCommand struct {
	name        string
	description string
	callback    func() error
	location    *config
}

func initConfig(index int) config {
	next := fmt.Sprintf("https://pokeapi.co/api/v2/location-area//")
	prev := fmt.Sprintf("")

	c := config{
		nextURL:     next,
		previousURL: prev,
	}
	return c
}

func newRegistry() map[string]cliCommand {
	registry := make(map[string]cliCommand)
	c := initConfig(1)

	registry["exit"] = cliCommand{
		name:        "exit",
		description: "Exit the Pokedex",
		callback:    commandExit,
		location:    &c,
	}

	registry["help"] = cliCommand{
		name:        "help",
		description: "Displays a help message",
		callback: func() error {
			return commandHelp(registry)
		},
		location: &c,
	}

	registry["map"] = cliCommand{
		name:        "map",
		description: "Displays the names of the next 20 location areas in the Pokemon world",
		callback: func() error {
			return commandMap(&c)
		},
		location: &c,
	}

	registry["mapb"] = cliCommand{
		name:        "mapb",
		description: "Displays the names of the last 20 location areas",
		callback: func() error {
			return commandMapb(&c)
		},
		location: &c,
	}

	return registry
}

func cleanInput(text string) []string {
	var strs []string
	lower := strings.ToLower(text)
	strs = strings.Fields(lower)
	return strs
}

func commandExit() error {
	fmt.Println("Closing the Pokedex... Goodbye!")
	os.Exit(0)
	return nil
}

func commandHelp(registry map[string]cliCommand) error {
	fmt.Println("Welcome to the Pokedex!")
	fmt.Println("Usage:")

	for cmd := range registry {
		str := cmd + ": " + registry[cmd].description
		fmt.Println(str)
	}
	return nil
}

func commandMap(c *config) error {
	res, err := http.Get(c.nextURL)
	if err != nil {
		return err
	}

	body, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}

	defer res.Body.Close()
	if res.StatusCode > 299 {
		return fmt.Errorf("Response failed with status code: %d and \nbody: %s\n", res.StatusCode, body)
	}

	data := AutoGenerated{}
	e := json.Unmarshal(body, &data)
	if e != nil {
		return err
	}
	for i := range 20 {
		fmt.Println(data.Results[i].Name)
	}
	//update urls
	if prev, ok := data.Previous.(string); ok {
		c.previousURL = prev
	} else {
		c.previousURL = ""
	}
	c.nextURL = data.Next
	return nil
}

func commandMapb(c *config) error {
	if c.previousURL == "" || c.previousURL == "null" {
		fmt.Println("you're on the first page")
		return nil
	}
	res, err := http.Get(c.previousURL)
	if err != nil {
		return err
	}

	body, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}

	defer res.Body.Close()
	if res.StatusCode > 299 {
		return fmt.Errorf("Response failed with status code: %d and \nbody: %s\n", res.StatusCode, body)
	}

	data := AutoGenerated{}
	e := json.Unmarshal(body, &data)
	if e != nil {
		return err
	}
	for i := range 20 {
		fmt.Println(data.Results[i].Name)
	}

	c.nextURL = data.Next
	if prev, ok := data.Previous.(string); ok {
		c.previousURL = prev
	} else {
		c.previousURL = ""
	}

	return nil
}
